# Generated by Django 4.2.4 on 2023-08-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('phoned', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('YT', 'youtube'), ('Google', 'Google'), ('NewsLetter', 'NewsLetter')], max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('special_files', models.FileField(blank=True, null=True, upload_to='')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
            ],
        ),
    ]
